### ISSUE TITLE
Vite 2.5 Cannot read property '_addedImports' of undefined

### ISSUE THREAD

**Issue by sporto** [hmsk/vite-plugin-elm#66] opened 2021-08-17 10:58 UTC
This plug-in works fine in vite 2.4 But with 2.5 I'm getting this (redacted):

```
Internal server error: Cannot read property '_addedImports' of undefined
Plugin: vite-plugin-elm
vite    |   File: [..]/spa/.elm-spa/defaults/Main.elm
vite    |       at addWatchFile ([..]/spa/node_modules/vite/dist/node/chunks/dep-98dbe93b.js:51077:19)
vite    |       at Array.forEach (<anonymous>)
vite    |       at TransformContext.transform ([..]/spa/node_modules/vite-plugin-elm/dist/index.js:427:34)
vite    |       at async Object.transform ([..]/spa/node_modules/vite/dist/node/chunks/dep-98dbe93b.js:51311:30)
vite    |       at async transformRequest ([..]/spa/node_modules/vite/dist/node/chunks/dep-98dbe93b.js:67150:29)
```

Thanks

**Comment by hmsk** [comment] 2021-08-25 07:43
Thanks for your report! The problem is fixed in [v2.4.3](https://www.npmjs.com/package/vite-plugin-elm/v/2.4.3) thanks to @nnnnathann 🙌 it'll be great if you check with updating and how it goes.

**Closed by hmsk** 2021-08-25 07:43 UTC
