### ISSUE TITLE
Dependencies outside of src directory do not get watched.

### ISSUE THREAD

**Issue by FranzSkuffka** [hmsk/vite-plugin-elm#16] opened 2021-05-25 15:43 UTC
My directory structure is as follows
```
/frontend
  /Main.elm
  /elm.json
/framework
  /frontend
    /Router.elm
```

In my elm.json I have `"source-directories": [".", "../framework/frontend"]`.

There are two subsequent problems that I solved in my local copy of the plugin but I am not sure if I broke something else.

1. **When I save `Router.elm` there is no compilation triggered at all.** That is, `handleHotUpdate` never gets called.     This is how I tested it: 
```js
handleHotUpdate({ file, server, modules }) {
            console.log('hot', file)
            // ...
```

How I fix it:

Below line 401 (https://github.com/hmsk/vite-plugin-elm/blob/main/src/index.ts#L402) I insert:
```
            dependencies.forEach(dep => {
                this.addWatchFile(dep)
            })
```

2. **If Router.elm breaks once, it gets removed from the `compileableFiles` set:** https://github.com/hmsk/vite-plugin-elm/blob/main/src/index.ts#L411. Then it is not found in the compilableFiles anymore: https://github.com/hmsk/vite-plugin-elm/blob/main/src/index.ts#L379

If I comment this out the `compileableFiles.delete` it works without problems.

**What is the purpose of `compileableFiles`? What am I breaking with this modification?**

**Comment by FranzSkuffka** [comment] 2021-05-25 19:14
Also it seems that files that have been created after the initial run do not get watched.

**Comment by FranzSkuffka** [comment] 2021-05-25 19:43
The whole compilableFiles logic is causing trouble for me, can you please enlighten me on this :)

**Comment by hmsk** [comment] 2021-05-26 08:36
Thanks for the detailed report! will look into it.

**Comment by hmsk** [comment] 2021-05-31 10:55
Fixed in https://github.com/hmsk/vite-plugin-elm/releases/tag/v2.3.1

**Closed by hmsk** 2021-05-31 10:55 UTC

**Comment by hmsk** [comment] 2021-05-31 10:56
> Also it seems that files that have been created after the initial run do not get watched.

I didn't pursue about this but let me know the detail to reproduce if this is still the thing.

**Comment by hmsk** [comment] 2021-05-31 11:04
`compilableFiles` is just a map to determine importer Elm file from importee's hot module update event. Since it's `.elm`, vite can't resolve imported files, this plugin need to behave behalf of vite.

**Comment by FranzSkuffka** [comment] 2021-05-31 14:23
Yes, this is still a problem.

**Comment by hmsk** [comment] 2021-05-31 18:43
Could you elaborate how I can reproduce that properly? 🙏

I tried below with guessing what you mean, but couldn't reproduce your problem:

1. Start vite
1. Add a new file `Other.elm` in outside of source directory (like your `Router.elm`)
1. Import ^ in `Main.elm` in main src dir and save
1. HMR happens for `Main.elm` and `Other.elm` is involved
1. Editing `Other.elm` makes HMR happens
