### ISSUE TITLE
Not working after Elm error

### ISSUE THREAD

**Issue by icidasset** [hmsk/vite-plugin-elm#9] opened 2021-04-30 20:56 UTC
Hey 👋  Thank you for this plugin!

I'm wondering if I'm doing something wrong or not. Whenever I make a change that results in an Elm compilation error, it seems like the vite server stops working and I have to restart it. Hot module reloading stops working, and a manual page refresh shows a blank page with the error message:
```
Uncaught SyntaxError: The requested module '/Application/Main.elm?t=1619816081719&import' does not provide an export named 'Elm'
```

Any thoughts on how to resolve this?

Additional notes:
v2.1.2 of this plugin with vite v2.2.3

**Comment by hmsk** [comment] 2021-05-01 23:30
Thanks for your feedback. I couldn't reproduce the exact situation you're talking about HMR.

As far as I play with `/example` dir, when gets a compilation error due to Elm code, we can get console error messages and HMR can happen when the problem is resolved.
![image](https://user-images.githubusercontent.com/85887/116797342-8ef3e980-aa99-11eb-8ec4-e8116b1196fb.png)

However, reloading the whole page doesn't work as your point. I think this plugin can be more developer-friendly to give error information, so I may work on improvement.

**Comment by luizpvas** [comment] 2021-05-15 19:23
@hmsk Thank you for this plugin as well!

I think I ran into the same problem as icidasset. Here is a short video I recorded:

![elm-2021-05-15_16 18 39](https://user-images.githubusercontent.com/4276593/118375673-94712980-b599-11eb-85f4-3d17938c1fbb.gif)

You said you couldn't reproduce the issue, let me know if I can help with more details. Thanks!

**Comment by hmsk** [comment] 2021-05-15 20:06
@luizpvas thanks! could you provide a minimum repo and steps to repro? I guess I didn't check depending module's HMR 💡

**Comment by hmsk** [comment] 2021-05-18 04:52
Fixed in #12 and 0485d8875340a1abb32594992eae8b90e6765ada 🎊

**Closed by hmsk** 2021-05-18 04:52 UTC

**Comment by icidasset** [comment] 2021-05-18 12:57
Thanks @hmsk ! 🙌 
Can confirm that reloading now works.

I'm still having trouble with HMR after the error though, but weirdly enough, not for the `Main.elm` module. So in other words, `src/Application/Main.elm` reloads after the error with HMR, `src/Application/Ingredients/View.elm` does not.

A `handleHotUpdate` call is being made, so I'm guessing my module is not being picked up here? https://github.com/hmsk/vite-plugin-elm/blob/main/src/index.ts#L379-L382

**Comment by hmsk** [comment] 2021-05-23 21:57
Thanks for the report! Probably #13 solves the case I guess. will update you when it's released.

**Comment by hmsk** [comment] 2021-05-31 11:06
Hey @icidasset, could you try with v2.3.1?

**Comment by icidasset** [comment] 2021-05-31 15:26
> Hey @icidasset, could you try with v2.3.1?

No luck I'm afraid 😥 If you can point me in the right direction regarding what to tweak, I could mess around to get it working?

**Comment by hmsk** [comment] 2021-05-31 19:10
I have no idea what's going on in your end. let's have a concrete example between us?

I created a repo with v2.3.1 to try to reproduce your problem
https://github.com/hmsk/vite-plugin-elm-issue-9

This vite project has
- `src/Main.elm`
- `src/Ingredients/View.elm`

Then tried below, but couldn't see any problem
1. Start vite server and see index page which loads `Main.elm` through `src/main.js`
1. Edit `Main.elm` to make an error
1. Reload the page
1. Edit `View.elm` and save it

https://user-images.githubusercontent.com/85887/120232697-f0c68100-c208-11eb-929f-48f20543c0b1.mp4

Could you point me what I'm wrong and provide changes for the repo to reproduce your problem? Thanks for your generous cooperation!

**Comment by icidasset** [comment] 2021-06-01 14:32
@hmsk Weird, that example repo does work for me 🤔 👌 
By the way, I was testing a "compilation failure" in `Ingredients/View.elm`, and then trying to correct the error.
Which I didn't think you showed in the video, but it does actually work with your example repo.

Anyhow, when I have time I'll try tweaking the code so I can get it working.
I'll also send you the code once I can open-source it.
